spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
server:
  port: 1000
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.spring.api.model
weather:
  api:
    url: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtFcst"
    key: "opV76JHAiKh6IJH3slJZ%2FehqPP8EBGXFGc7B1JXb%2BOMfnx%2BmYKljlDXhMoJNwrxX4bvyUjglvUpUYl7TmgRFWA%3D%3D"
