services:
  info:
    build:
      context: c:\Users\hi-pc-999\Desktop\msa-practice\service\info
      dockerfile: Dockerfile
    depends_on:
      - mysql
    image: "info"
    container_name: "info"
    ports:
      - 1002:1002
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/info?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
  
  member:
    build:
      context: c:\Users\hi-pc-999\Desktop\msa-practice\service\member
      dockerfile: Dockerfile
    depends_on:
      - mysql
    image: "member"
    container_name: "member"
    ports:
      - 1003:1003
    environment:
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql:3306/member
      - INFO_URL=http://info:1002

  mysql:
    image: "mysql:latest"
    container_name: "mysql"
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql