spring:
  application:
    name: spring-security
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 1001
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.spring.springsecurity.model
jwt:
  issuer: test@gmail.com
  secret_key: fmcoI6HlpOzcdyXhxqsUfMo1yf9sI8iswHykTF6Kwf2c9V7+ijsjkY81tJU/2VFx84beOs95iXfTUAJk5PphGw==